### ISSUE TITLE
add slot usage on identifier column?

### ISSUE THREAD

**Issue by turbomam** [linkml/schemasheets#26] opened 2022-03-04 15:50 UTC

**Comment by cmungall** [comment] 2022-03-07 16:00
can you give more context?

**Comment by turbomam** [comment] 2022-03-14 15:32
I think we discussed this somewhere else, so I'll try to look that up. Maybe even another GH issue!

I would like to make slot usage assertions about columns that have been set as identifiers at the schema level. The use case is saying where slots should appear as columns in DataHarmonizer. We have been doing that with assertions but will be switching to slot groups and ranks.

Assume I 
- define the slot, with the identifier assertion, on its own row in schemasheets
- define a class on it's own row
- use a third row, mentioning the class and the slot, to make slot usage assertions

LinkML doesn't like that, because then I have an `id` slot on class `biosample` (inherited from `named thing`) and `biosample_id` from the slot usage.

**Comment by cmungall** [comment] 2022-03-15 15:40
are you trying to deliberately override the name to rename `id` and `biosample_id`?

I suspect what the issue is here is that the slot_usage causes a name mangling - can you say where this manifests?

**Comment by turbomam** [comment] 2022-07-26 18:02
this issue overlaps with the broader LinkML questions
- why can't a class have multiple identifiers
- why isn't there a `unique` attribute for slots
- compound unique_keys ? seems complicated

**Comment by sierra-moxon** [comment] 2023-03-24 22:00
we now have compound keys.  closing as complete, please reopen if necessary. :)

**Closed by sierra-moxon** 2023-03-24 22:00 UTC
